version: '3'

services:
  service_1:
    build:
      context: .
      dockerfile: Dockerfile
      target: service_1
    environment:
      - PATH_PREFIX=/api/service_1
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.zoc0g0g-0-http.rule=Host(`${HOST}`) && PathPrefix(`/api/service_1`)'
      - traefik.http.routers.zoc0g0g-0-http.entryPoints=http
      - traefik.http.routers.zoc0g0g-0-http.middlewares=gzip
      - coolify.managed=true
      - 'coolify.applicationId=${APPLICATION_ID}'
      - coolify.type=application

  service_2:
    build:
      context: .
      dockerfile: Dockerfile
      target: service_2
    environment:
      - PATH_PREFIX=/api/service_2
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.zoc0g0g-0-http.rule=Host(`${HOST}`) && PathPrefix(`/api/service_2`)'
      - traefik.http.routers.zoc0g0g-0-http.entryPoints=http
      - traefik.http.routers.zoc0g0g-0-http.middlewares=gzip
      - coolify.managed=true
      - 'coolify.applicationId=${APPLICATION_ID}'
      - coolify.type=application

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.zoc0g0g-0-http.rule=Host(`${HOST}`) && PathPrefix(`/`)'
      - traefik.http.routers.zoc0g0g-0-http.entryPoints=http
      - traefik.http.routers.zoc0g0g-0-http.middlewares=gzip
      - coolify.managed=true
      - 'coolify.applicationId=${APPLICATION_ID}'
      - coolify.type=application
      - traefik.http.middlewares.custom-auth.basicauth.users=test:$$2y$$12$$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG
      - traefik.http.routers.q04o0gk-0-http.middlewares=custom-auth
