version: '3'

services:
    service_1:
        build:
            context: .
            dockerfile: Dockerfile
            target: service_1
        environment:
            - PATH_PREFIX=/api/service_1
            - PORT=3001
        labels:
            - traefik.enable=true
            - 'traefik.http.routers.zoc0g0g-0-http.rule=Host(`${HOST}`) && PathPrefix(`/api/service_1`)'
            - traefik.http.routers.zoc0g0g-0-http.entryPoints=http
            - traefik.http.routers.zoc0g0g-0-http.middlewares=gzip
            - 'coolify.applicationId=${APPLICATION_ID}'
            - coolify.type=application
            - coolify.managed=true
            - coolify.version=4.0.0-beta.196
            - coolify.name=service_1
            - coolify.pullRequestId=0
        networks:
            coo0ccc: null
        restart: unless-stopped
        container_name: service_1

    service_2:
        build:
            context: .
            dockerfile: Dockerfile
            target: service_2
        environment:
            - PATH_PREFIX=/api/service_2
            - PORT=3002
        labels:
            - traefik.enable=true
            - 'traefik.http.routers.zoc0g0g-0-http.rule=Host(`${HOST}`) && PathPrefix(`/api/service_2`)'
            - traefik.http.routers.zoc0g0g-0-http.entryPoints=http
            - traefik.http.routers.zoc0g0g-0-http.middlewares=gzip
            - 'coolify.applicationId=${APPLICATION_ID}'
            - coolify.type=application
            - coolify.managed=true
            - coolify.version=4.0.0-beta.196
            - coolify.name=service_2
            - coolify.pullRequestId=0
        networks:
            coo0ccc: null
        restart: unless-stopped
        container_name: service_2

    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: web
        labels:
            - traefik.enable=true
            - 'traefik.http.routers.zoc0g0g-0-http.rule=Host(`${HOST}`) && PathPrefix(`/`)'
            - traefik.http.routers.zoc0g0g-0-http.entryPoints=http
            - traefik.http.routers.zoc0g0g-0-http.middlewares=gzip
            - 'coolify.applicationId=${APPLICATION_ID}'
            - coolify.type=application
            - coolify.managed=true
            - coolify.version=4.0.0-beta.196
            - coolify.name=web
            - coolify.pullRequestId=0
        networks:
            coo0ccc: null
        restart: unless-stopped
        container_name: web
networks:
    coo0ccc:
        name: coo0ccc
        external: true
