version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: web
        networks:
            coo0ccc: null
        restart: unless-stopped
        container_name: web
