FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Install nodemon globally
RUN npm install -g nodemon

WORKDIR /usr/src/app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy source files
COPY . .

# Use nodemon for development
CMD ["nodemon", "--watch", "src", "--exec", "pnpm", "start"]