version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: web
        restart: unless-stopped
        container_name: web-i8s4c0s-210455319065
        networks:
            i8s4c0s: null
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            # - traefik.http.routers.http-0-z4kwksc.entryPoints=redirect-to-https
            - 'traefik.http.routers.http-0-z4kwksc.rule=Host(`asd.ahammer.work`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-z4kwksc.middlewares=gzip
            - traefik.http.routers.https-0-z4kwksc.entryPoints=https
            - traefik.http.routers.https-0-z4kwksc.middlewares=gzip
            - 'traefik.http.routers.https-0-z4kwksc.rule=Host(`asd.ahammer.work`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-z4kwksc.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-z4kwksc.tls=true
            - coolify.managed=true
            - coolify.version=4.0.0-beta.198
            - coolify.applicationId=10
            - coolify.type=application
            - coolify.name=web-i8s4c0s-210455319065
            - coolify.pullRequestId=0
volumes: {}
networks:
    i8s4c0s:
        name: i8s4c0s
        external: true
