version: '3'

services:
    service_1:
        build:
            context: .
            dockerfile: Dockerfile
            target: service_1
        volumes:
            - ./apps/service_1/src:/usr/src/app/src
            - ./apps/service_1/package.json:/usr/src/app/package.json
            - ./apps/service_1/pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
        environment:
            - NODE_ENV=development
            - PORT=3001
        ports:
            - '3001:3001'
        command: ['nodemon', '--watch', 'src', '--exec', 'pnpm', 'start']

    service_2:
        build:
            context: .
            dockerfile: Dockerfile
            target: service_2
        volumes:
            - ./apps/service_2/src:/usr/src/app/src
            - ./apps/service_2/package.json:/usr/src/app/package.json
            - ./apps/service_2/pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
        environment:
            - NODE_ENV=development
            - PORT=3002
        ports:
            - '3002:3002'
        command: ['nodemon', '--watch', 'src', '--exec', 'pnpm', 'start']

    db:
        image: postgres:17-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - db:/var/lib/postgresql/data

    cache:
        image: redis:7.4-alpine
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data

volumes:
    db:
    cache:
