version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: web
        restart: unless-stopped
        container_name: web-po48wco-205141202003
